import {
	Editor,
	MarkdownView,
	MarkdownFileInfo,
	Plugin,
	Notice,
} from "obsidian";
import { TickTickClient } from "ticktickClient";
import { OpenAIClient } from "openaiClient";

export class CreateTaskFromSelectionCommand {
	constructor(
		private plugin: Plugin,
		private ticktick: TickTickClient | undefined,
		private openai: OpenAIClient | undefined
	) {}

	register() {
		this.plugin.addCommand({
			id: "create-task-from-selection",
			name: "Create task from selection",
			editorCallback: (
				editor: Editor,
				view: MarkdownView | MarkdownFileInfo
			) => {
				this.run(editor);
			},
		});
	}

	async run(editor: Editor) {
		const selection = editor.getSelection();
		console.debug("[TaskFromNote] selected text:", selection);

		if (!selection) {
			new Notice("No text selected");
			return;
		}

		if (!this.ticktick) {
			new Notice(
				"TickTick is not configured. Get access token in plugin settings"
			);
			return;
		}

		if (!this.openai) {
			new Notice(
				"OpenAI is not configured. Set model in plugin settings"
			);
			return;
		}

		let aiResponse: string;

		try {
			new Notice("Send query to OpenAI. Please, wait...");

			aiResponse = await this.openai.chat(
				selection,
				`You are an assistant that turns the user's text into a task for a task manager.
			  
			  1. Write your answer strictly in the same language as the user’s request.
			  2. Analyze the user’s text and formulate ONE task.
			  3. Return the result in the following JSON format:
			  {
				"title": "...",
				"description": "..."
			  }
			  
			  Field requirements:
			  - "title" — a short, clear task title (one line, no period at the end).
			  - "description" — a concise but clear description: what needs to be done, important details, and success criteria.
			  
			  Do not add any explanations, surrounding text, or comments — only raw JSON.`
			);
			console.debug(
				"[TaskFromNote] task successfully generated by OpenAI:",
				aiResponse
			);
			new Notice("Task generated by OpenAI");
		} catch (e) {
			console.error("[TaskFromNote] OpenAI request error", e);
			new Notice("Failed to generate task, see console");
			return;
		}

		let taskData: { title: string; description: string };
		try {
			taskData = JSON.parse(aiResponse);
			console.debug("[TaskFromNote] parsed AI task:", taskData);
		} catch (e) {
			console.error("[TaskFromNote] failed to parse AI JSON:", e);
			console.error(
				"[TaskFromNote] raw AI response for debug:",
				aiResponse
			);
			new Notice("Failed to parse AI task JSON, see console");
			return;
		}

		try {
			const result = await this.ticktick.createTask({
				title: taskData.title,
				content: taskData.description,
			});
			console.debug("[TaskFromNote] task successfully created:", result);
			new Notice("Task created in TickTick");
		} catch (e) {
			console.error("[TaskFromNote] TickTick createTask error", e);
			// eslint-disable-next-line obsidianmd/ui/sentence-case
			new Notice("Failed to create TickTick task, see console");
		}
	}
}
